apiVersion: apps/v1

kind: Deployment

metadata:

  name: hello-gitops

spec:

  replicas: 1

  selector:

    matchLabels:

      app: hello-gitops

  template:

    metadata:

      labels:

        app: hello-gitops

    spec:

      containers:

      - name: hello-gitops

        image: lordsam07/gitops-python:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 5000
